---
- name: Generate a report on XZ versions
  hosts: Greg-rocky9
  gather_facts: false
  vars:
  tasks:
    - name: Shell command to gather XZ versions
      ansible.builtin.shell: xz --version
      register: xz_version

      # stdout_lines": [
      # "xz (XZ Utils) 5.2.5",   
    - name: Display xz_version to screen 
      when: xz_version.stdout_lines[0] == "xz (XZ Utils) 5.2.5" or xz_version.stdout_lines[0] == "xz (XZ Utils) 5.6.1"
      ansible.builtin.debug:
        # var: xz_version
        msg: "{{ inventory_hostname }} is vulnerable to the exploit {{ xz_version.stdout_lines[0] }}"